### ISSUE TITLE
Design (multithreaded ?) question regarding fuse-native/vs fuse-bindings

### ISSUE THREAD

**Issue by 131** [fuse-friends/fuse-native#12]
Previously, using fuse-bindings, and reading an mkv file, VLC requested for continious ranges of bytes (e.g. 4=>6, 6=>8, 8=>10, ..) 

Now using fuse-native, it sometimes read ranges in a non serial way (e.g. requesting 4=>6, 8=>10, 6=>8)

Is it the "normal" behavior due to the multitread gain of fuse-native vs fuse-bindings ? If so, I've got a __lot__ of changes in [random-read-http](https://www.npmjs.com/package/random-read-http) to make !

**Comment by mafintosh** [comment]
Yea, that's how fuse does it, it seems.
