### ISSUE TITLE
Modified and Access times

### ISSUE THREAD

**Issue by microwavesafe** [fuse-friends/fuse-native#14]
Using the example as a basis I am passing an object containing mtime, atime and ctime

```
            mtime: attr.modified,
            atime: attr.modified,
            ctime: attr.modified,
            nlink: 1,
            size: attr.size,
            mode: mode,
            uid: process.getuid(),
            gid: process.getgid(),
```

back from to readdir and gettattr, where attr is my object with correct data.  No matter what JS date object I put as mtime / atime / ctime, when looking at properties in nautilus, it always reads back with the current date time.

I have tried manually setting the times to `new Date(5000000)` in the callbacks, but they still always give me the current date and time.

Is this a limitation of the current implementation or am I doing something wrong?

**Comment by mafintosh** [comment]
Which version of fuse-native are you using? We've been returning custom mtimes without issues in our own stuff

**Comment by microwavesafe** [comment]
Thanks, I hadn't been paying attention and you've already fixed it. After running npm install again it works.
