### ISSUE TITLE
Invalidate cache

### ISSUE THREAD

**Issue by microwavesafe** [fuse-friends/fuse-native#8]
I've been using this library successfully with Linux and node 13, so thanks for creating it.

I was wondering if there was a way to force the OS to request a readdir? I found fuse_invalidate_path which sounded promising. But I couldn't find anything similar in this library.

What I'm trying to achieve is the file browser automatically updating when my program updates the filesystem. Without the user having to refresh.

**Comment by mafintosh** [comment]
Try setting autoCache: true in the fuse constructor. That should do the trick.

**Comment by microwavesafe** [comment]
Thanks, I'll give this a go and reopen if I have any problems with it.
